//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGrooming.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Owner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Owner()
        {
            this.tbl_Dog = new HashSet<tbl_Dog>();
        }
    
        public string OwnerID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email_Address { get; set; }
        public int Phone_Number { get; set; }
        public string Address { get; set; }
        public string Owner_Reviews { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Dog> tbl_Dog { get; set; }
    }
}
