//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGrooming.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Dog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Dog()
        {
            this.tbl_Appointment = new HashSet<tbl_Appointment>();
        }
    
        public string DogID { get; set; }
        public string OwnerID { get; set; }
        public string Dogname { get; set; }
        public string Gender { get; set; }
        public string Breed { get; set; }
        public System.DateTime DOB { get; set; }
        public string Age { get; set; }
        public string Matted_dog { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Appointment> tbl_Appointment { get; set; }
        public virtual tbl_Owner tbl_Owner { get; set; }
    }
}
