//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGrooming.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ServiceRendered
    {
        public string AppointmentID { get; set; }
        public int LineItemNumber { get; set; }
        public string ServiceID { get; set; }
        public float ServiceExtendedPrice { get; set; }
        public string EmployeeID { get; set; }
    
        public virtual tbl_Appointment tbl_Appointment { get; set; }
        public virtual tbl_Employee tbl_Employee { get; set; }
        public virtual tbl_GroomingServices tbl_GroomingServices { get; set; }
    }
}
