//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGrooming.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_GroomingServices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_GroomingServices()
        {
            this.tbl_ServiceRendered = new HashSet<tbl_ServiceRendered>();
        }
    
        public string ServiceID { get; set; }
        public string ServiceName { get; set; }
        public string ServiceDuration { get; set; }
        public float ServicePrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ServiceRendered> tbl_ServiceRendered { get; set; }
    }
}
